unit u_AlbumClass;

interface

uses
  MVCFramework.Swagger.Commons, // Documentação Swagger
  MVCFramework.ActiveRecord,
  MVCFramework.Serializer.Commons,
  u_ArtistaClass;

type
  [MVCNameCaseAttribute(ncLowerCase)]
  [MVCTableAttribute('Album')]
  TAlbum = class(TArtista)
  [MVCEntityActionsAttribute([eaCreate, eaRetrieve, eaUpdate, eaDelete])]
  private
    [MVCTableFieldAttribute('alb_id', [foPrimaryKey, foAutoGenerated])]
    Falb_id: Integer;

    [MVCTableFieldAttribute('alb_nome')]
    Falb_nome: string;

    [MVCTableFieldAttribute('id_art')]
    Fid_art: Integer;
  public
    [MVCSwagJSONSchemaFieldAttribute(stInteger, 'alb_id', 'ID do Album', True)]
    property alb_id: Integer read Falb_id write Falb_id;

    [MVCSwagJSONSchemaFieldAttribute(stString, 'alb_nome', 'Nome do Album', True)]
    property alb_nome: string read Falb_nome write Falb_nome;

    [MVCSwagJSONSchemaFieldAttribute(stInteger, 'id_art', 'ID do Artista', True)]
    property id_art: Integer read Fid_art write Fid_art;
  end;

implementation

end.
