unit u_CapaClass;

interface

uses
  MVCFramework.Swagger.Commons, // Documentação Swagger
  MVCFramework.ActiveRecord,
  MVCFramework.Serializer.Commons,
  Vcl.imaging.jpeg, Vcl.ExtCtrls,
  u_AlbumClass;

type
  [MVCNameCaseAttribute(ncLowerCase)]
  [MVCTableAttribute('Capa')]
  TCapa = class(TAlbum)
  [MVCEntityActionsAttribute([eaCreate, eaRetrieve, eaUpdate, eaDelete])]
  private
    [MVCTableFieldAttribute('cp_id', [foPrimaryKey, foAutoGenerated])]
    Fcp_id: Integer;

    [MVCTableFieldAttribute('id_alb')]
    Fid_alb: Integer;

    [MVCTableFieldAttribute('cp_nome')]
    Fcp_nome: string;

    [MVCTableFieldAttribute('cp_url')]
    Fcp_url: string;
  public
    [MVCSwagJSONSchemaFieldAttribute(stInteger, 'cp_id', 'ID da Capa', True)]
    property cp_id: Integer read Fcp_id write Fcp_id;

    [MVCSwagJSONSchemaFieldAttribute(stInteger, 'id_alb', 'ID do Album', True)]
    property id_alb: Integer read Fid_alb write Fid_alb;

    [MVCSwagJSONSchemaFieldAttribute(stString, 'cp_nome', 'Nome da Capa', True)]
    property cp_nome: String read Fcp_nome write Fcp_nome;

    [MVCSwagJSONSchemaFieldAttribute(stString, 'cp_url', 'URL da Capa', True)]
    property cp_url: String read Fcp_url write Fcp_url;
  end;

implementation

end.
