
SELECT * FROM ARTISTA;
SELECT * FROM ALBUM;

SELECT * FROM ARTISTA ART 
   LEFT OUTER JOIN ALBUM ALB ON ALB.ID_ART = ART.ART_ID
   LEFT OUTER JOIN CAPA CAP ON CAP.ID_ALB = ALB.ALB_ID ;
WHERE ART.ART_NOME LIKE "%MIKE%";   

SELECT * FROM ALBUM ALB 
   INNER JOIN ARTISTA ART ON ALB.ART_ID = ART.ART_ID;

SELECT * FROM ARTISTA ART 
   INNER JOIN ALBUM ALB ON ART.ART_ID = ALB.ID_ART
   INNER JOIN CAPA CAP ON CAP.ID_ALB = ALB.ALB_ID;
      
SELECT * FROM CAPA;

		