
SELECT * FROM ARTISTA;
SELECT * FROM ALBUM;
SELECT * FROM CAPA;

-- ARTISTA
SELECT * FROM ARTISTA ART 
   LEFT OUTER JOIN ALBUM ALB ON ALB.ID_ART = ART.ART_ID
   LEFT OUTER JOIN CAPA CAP ON CAP.ID_ALB = ALB.ALB_ID ;
-- ARTISTA

-- ALBUM
SELECT * FROM ALBUM ALB 
   LEFT OUTER JOIN ARTISTA ART ON ART.ART_ID = ALB.ID_ART
   LEFT OUTER JOIN CAPA CAP ON CAP.ID_ALB = ALB.ALB_ID ;
-- ALBUM

-- CAPA
SELECT * FROM CAPA CAP 
 LEFT OUTER JOIN ALBUM ALB ON ALB.ALB_ID = CAP.ID_ALB  
 LEFT OUTER JOIN ARTISTA ART ON ART.ART_ID = ALB.ID_ART; 		
-- CAPA 